<?php

declare(strict_types=1);

require_once __DIR__ . '/engine.php';
require_once __DIR__ . '/meta-generator.php';
require_once __DIR__ . '/link-builder.php';

$engine = new SeoEngine();
$pdo = $engine->pdo;

$pending = $pdo->query("SELECT id, entity_type, entity_id FROM seo_generation_queue WHERE status='pending' ORDER BY created_at ASC LIMIT 500")->fetchAll();
$update = $pdo->prepare("UPDATE seo_generation_queue SET status=:status, updated_at=NOW() WHERE id=:id");
$upsertPage = $pdo->prepare("INSERT INTO seo_pages (entity_type, entity_id, page_path, slug, html, meta_title, meta_description, canonical_url, last_generated_at)
    VALUES (:entity_type, :entity_id, :page_path, :slug, :html, :meta_title, :meta_description, :canonical_url, NOW())
    ON DUPLICATE KEY UPDATE html=VALUES(html), meta_title=VALUES(meta_title), meta_description=VALUES(meta_description), canonical_url=VALUES(canonical_url), last_generated_at=NOW()");

$generateParagraphs = static function (array $context): string {
    $lines = [
        sprintf('This page provides verified postal information for %s in %s, %s.', $context['name'], $context['district'] ?? $context['state'], $context['state'] ?? 'India'),
        'The data set is refreshed automatically from the India Post aligned database, ensuring the latest post office and delivery classifications.',
        'You can use this page to identify serviceable areas, locate nearby offices, and cross-check regional routing before sending parcels or letters.',
        'For better navigation, related pincodes from the same district and state are linked below to reduce search friction and improve discoverability.',
        'Each record includes location hierarchy details useful for government forms, ecommerce address validation, and logistics planning.',
        'When new records are added to the database, this page is regenerated by the SEO engine and sitemap files are refreshed for faster indexing.',
        'Use the linked district and state directories for broader coverage, or move to nearby pincode pages for hyperlocal lookup.',
        'The structured schema markup embedded in this page helps search engines understand regional entities, breadcrumb paths, and common user questions.',
        'If you are looking for all offices under this coverage, refer to the listed postal entries and service indicators included with every update.',
        'This auto-generated content is designed for users and crawlers with accurate, machine-readable context for high-scale discoverability.',
    ];

    while (str_word_count(implode(' ', $lines)) < 520) {
        $lines[] = 'Postal intelligence for India works best when pincode, district, and state references stay synchronized; this page keeps that alignment intact.';
    }

    return implode("\n\n", $lines);
};

foreach ($pending as $job) {
    try {
        $type = $job['entity_type'];
        $entity = $job['entity_id'];

        $context = [];
        $template = null;

        if ($type === 'pincode') {
            $stmt = $pdo->prepare("SELECT pincode, officename, district, statename FROM post_offices WHERE pincode=:id LIMIT 1");
            $stmt->execute(['id' => $entity]);
            $row = $stmt->fetch();
            if (!$row) {
                throw new RuntimeException('Missing pincode: ' . $entity);
            }

            $context = ['name' => 'Pincode ' . $row['pincode'], 'pincode' => $row['pincode'], 'district' => $row['district'], 'state' => $row['statename'], 'path' => '/pincode/' . $row['pincode'], 'area' => $row['officename']];
            $template = __DIR__ . '/../templates/pincode-template.php';
        } elseif ($type === 'district') {
            $name = str_replace('-', ' ', $entity);
            $stmt = $pdo->prepare("SELECT district, statename FROM post_offices WHERE LOWER(district)=LOWER(:district) LIMIT 1");
            $stmt->execute(['district' => $name]);
            $row = $stmt->fetch();
            if (!$row) {
                throw new RuntimeException('Missing district: ' . $entity);
            }
            $context = ['name' => $row['district'] . ' district', 'district' => $row['district'], 'state' => $row['statename'], 'path' => '/district/' . $engine->slugify($row['district'])];
            $template = __DIR__ . '/../templates/district-template.php';
        } elseif ($type === 'state') {
            $name = str_replace('-', ' ', $entity);
            $stmt = $pdo->prepare("SELECT statename FROM post_offices WHERE LOWER(statename)=LOWER(:state) LIMIT 1");
            $stmt->execute(['state' => $name]);
            $state = (string) $stmt->fetchColumn();
            if ($state === '') {
                throw new RuntimeException('Missing state: ' . $entity);
            }
            $context = ['name' => $state . ' state', 'state' => $state, 'district' => $state, 'path' => '/state/' . $engine->slugify($state)];
            $template = __DIR__ . '/../templates/state-template.php';
        } elseif ($type === 'area') {
            $name = str_replace('-', ' ', $entity);
            $stmt = $pdo->prepare("SELECT officename, district, statename, pincode FROM post_offices WHERE LOWER(officename)=LOWER(:area) LIMIT 1");
            $stmt->execute(['area' => $name]);
            $row = $stmt->fetch();
            if (!$row) {
                throw new RuntimeException('Missing area: ' . $entity);
            }
            $context = ['name' => $row['officename'] . ' area', 'area' => $row['officename'], 'district' => $row['district'], 'state' => $row['statename'], 'pincode' => $row['pincode'], 'path' => '/area/' . $engine->slugify($row['officename'])];
            $template = __DIR__ . '/../templates/area-template.php';
        }

        if ($template === null) {
            throw new RuntimeException('Unsupported entity type: ' . $type);
        }

        $context['content'] = $generateParagraphs($context);
        $context['heading'] = ucfirst($type) . ' details for ' . ($context['pincode'] ?? $context['district'] ?? $context['state'] ?? $context['area']);
        $context['nearby_links'] = !empty($context['pincode']) ? buildNearbyPincodeLinks($pdo, (string) $context['pincode']) : [];
        $context['district_links'] = !empty($context['district']) ? buildDistrictLinks($pdo, (string) $context['district']) : [];
        $context['state_links'] = !empty($context['state']) ? buildStateLinks($pdo, (string) $context['state']) : [];

        $crumbs = [
            ['name' => 'Home', 'url' => '/'],
            ['name' => ucfirst($type), 'url' => $context['path']],
        ];
        $context['breadcrumb_html'] = implode(' / ', array_map(static fn (array $c): string => '<a href="' . $c['url'] . '">' . htmlspecialchars($c['name']) . '</a>', $crumbs));

        $schema = [
            ['@context' => 'https://schema.org', '@type' => 'WebSite', 'name' => 'India Pincode Locator', 'url' => $engine->baseUrl],
            ['@context' => 'https://schema.org', '@type' => 'SearchAction', 'target' => $engine->baseUrl . '/search?q={query}', 'query-input' => 'required name=query'],
            ['@context' => 'https://schema.org', '@type' => 'BreadcrumbList', 'itemListElement' => [
                ['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => $engine->baseUrl . '/'],
                ['@type' => 'ListItem', 'position' => 2, 'name' => ucfirst($type), 'item' => $engine->baseUrl . $context['path']],
            ]],
            ['@context' => 'https://schema.org', '@type' => 'FAQPage', 'mainEntity' => [
                ['@type' => 'Question', 'name' => 'How often is this pincode data updated?', 'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'The SEO engine checks for updates every hour and regenerates pages automatically.']],
                ['@type' => 'Question', 'name' => 'Can I find nearby pincodes?', 'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Yes, nearby pincodes and related district/state links are listed on each generated page.']],
            ]],
        ];
        $context['schema_json'] = json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        ob_start();
        $pageData = $context;
        include $template;
        $html = (string) ob_get_clean();

        $meta = MetaGenerator::forEntity($type, $context, $engine->baseUrl);
        $upsertPage->execute([
            'entity_type' => $type,
            'entity_id' => $entity,
            'page_path' => $context['path'],
            'slug' => trim(strrchr($context['path'], '/') ?: $context['path'], '/'),
            'html' => $html,
            'meta_title' => $meta['meta_title'],
            'meta_description' => $meta['meta_description'],
            'canonical_url' => $meta['canonical_url'],
        ]);

        $engine->writeCache($context['path'], $html);

        $update->execute(['status' => 'completed', 'id' => $job['id']]);
    } catch (Throwable $e) {
        $update->execute(['status' => 'failed', 'id' => $job['id']]);
        fwrite(STDERR, "Generation failed for job {$job['id']}: {$e->getMessage()}\n");
    }
}

echo 'Processed jobs: ' . count($pending) . PHP_EOL;
